#!/bin/bash
#
# MT7925 Bluetooth Fix Script
# Fixes MediaTek MT7925 BT not initializing on Linux
# Run as: sudo ./mt7925-bt-fix.sh [install|uninstall|status|test|logs]
#

# Note: Not using 'set -e' globally because modprobe -r returns non-zero
# when modules aren't loaded, which is expected behavior

SCRIPT_NAME="mt7925-bt-fix"
SERVICE_NAME="mt7925-bt-heal.service"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}"
SLEEP_HOOK="/usr/lib/systemd/system-sleep/${SCRIPT_NAME}"
LOG_FILE="/var/log/${SCRIPT_NAME}.log"
MODULE_RELOAD_SCRIPT="/usr/bin/${SCRIPT_NAME}-reload.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() {
	local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $1"
	echo -e "$msg"
	# Strip ANSI color codes before writing to log file
	local plain_msg
	plain_msg=$(echo "$msg" | sed 's/\x1b\[[0-9;]*m//g')
	echo "$plain_msg" >>"$LOG_FILE" 2>/dev/null || true
}

error() {
	log "${RED}ERROR: $1${NC}"
}

success() {
	log "${GREEN}$1${NC}"
}

info() {
	log "${YELLOW}$1${NC}"
}

# Check if running as root
check_root() {
	if [[ $EUID -ne 0 ]]; then
		error "This script must be run as root (use sudo)"
		exit 1
	fi
}

# Check if this is actually an MT7925 system
check_hardware() {
	info "Checking hardware..."

	# Check via lspci first (most reliable)
	if lspci -nn 2>/dev/null | grep -qi "MT7925"; then
		success "MT7925 wireless card detected"
		return 0
	fi

	# Fallback: check PCI device IDs generically
	if lspci -nn 2>/dev/null | grep -qi "14c3.*7925"; then
		success "MT7925 detected via PCI ID"
		return 0
	fi

	# Fallback: check sysfs
	if find /sys/bus/pci/devices -name "uevent" 2>/dev/null | xargs grep -l "14c3:7925" 2>/dev/null | grep -q .; then
		success "MT7925 detected via sysfs"
		return 0
	fi

	error "No MT7925 wireless card found. This script is for MT7925 only."
	exit 1
}

# Create the module reload script (called by systemd service)
create_reload_script() {
	cat >"$MODULE_RELOAD_SCRIPT" <<'SCRIPT'
#!/bin/bash
# Module reload script for MT7925 BT fix
# Generated by mt7925-bt-fix.sh

LOG_FILE="/var/log/mt7925-bt-fix.log"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Reloading MT7925 modules..." >> "$LOG_FILE"

# Remove all related modules (ignore errors if not loaded)
modprobe -r btusb btmtk mt7925e 2>/dev/null
sleep 1

# Load in correct order: wifi first, then bt drivers
if ! modprobe mt7925e; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Failed to load mt7925e" >> "$LOG_FILE"
    exit 1
fi
sleep 1

modprobe btmtk || echo "[$(date '+%Y-%m-%d %H:%M:%S')] Warning: btmtk load failed" >> "$LOG_FILE"
modprobe btusb || echo "[$(date '+%Y-%m-%d %H:%M:%S')] Warning: btusb load failed" >> "$LOG_FILE"
sleep 1

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Done" >> "$LOG_FILE"
SCRIPT
	chmod +x "$MODULE_RELOAD_SCRIPT"
}

# Reload all MT7925 BT modules in correct order
reload_modules() {
	info "Reloading MT7925 modules..."
	# Remove all related modules (ignore errors if not loaded)
	modprobe -r btusb btmtk mt7925e 2>/dev/null || true
	sleep 1

	# Load in correct order: wifi first, then bt drivers
	if ! modprobe mt7925e; then
		error "Failed to load mt7925e"
		return 1
	fi
	sleep 1

	modprobe btmtk || error "Failed to load btmtk (continuing anyway)"
	modprobe btusb || error "Failed to load btusb (continuing anyway)"
	sleep 1
}

# Wait for BT adapter to appear (with retry)
wait_for_bt_adapter() {
	local max_attempts=${1:-3}
	local attempt=1

	while [[ $attempt -le $max_attempts ]]; do
		if [[ -d /sys/class/bluetooth ]] && [[ -n "$(ls -A /sys/class/bluetooth 2>/dev/null)" ]]; then
			return 0
		fi
		info "Waiting for BT adapter... (attempt $attempt/$max_attempts)"
		sleep 2
		attempt=$((attempt + 1))
	done
	return 1
}

# Print power cycle reminder for MT7925 BT issues
print_powercycle_reminder() {
	echo ""
	echo "⚠️  If BT fails to initialize, try this power cycle procedure:"
	echo "    1. Full power cycle: Shut down, unplug, hold power 30s"
	echo "       This resets the internal USB BT controller's GPIO state,"
	echo "       which can get stuck after a normal shutdown."
	echo "    2. In UEFI/BIOS: Check WiFi/Bluetooth is enabled"
	echo "       (if present as single 'Wireless' option, enable it)"
	echo "    3. Toggle OFF → Save & Exit → Re-enter UEFI → Toggle ON → Save & Exit"
	echo "    4. Reboot"
	echo ""
}

# Prompt user to try power cycle first (may fix BT without needing the script)
prompt_powercycle_check() {
	echo ""
	echo "⚠️  Before installing, try this first — it may fix BT without needing the script:"
	echo ""
	print_powercycle_reminder
	read -p "Have you tried the power cycle and rebooted? (y/N) " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		echo "Please try the power cycle first, reboot, and test if Bluetooth works."
		echo "If it still doesn't work, run this install command again."
		exit 1
	fi
}

# Install the fix
do_install() {
	check_root
	check_hardware

	prompt_powercycle_check

	info "Installing MT7925 BT fix..."

	# Create the reload script first (used by both service and hook)
	create_reload_script
	success "Created ${MODULE_RELOAD_SCRIPT}"

	# Create service file (use <<EOF to expand variables)
	cat >"$SERVICE_FILE" <<EOF || {
[Unit]
Description=MT7925e Bluetooth Fix
After=bluetooth.service
Before=bluetooth.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=${MODULE_RELOAD_SCRIPT}
RemainAfterExit=yes
TimeoutSec=30

[Install]
WantedBy=multi-user.target
EOF
		error "Failed to create ${SERVICE_FILE}"
		exit 1
	}
	success "Created ${SERVICE_FILE}"

	# Create suspend/resume hook (use <<EOF to expand variables)
	cat >"$SLEEP_HOOK" <<EOF || {
#!/bin/bash
# Fix MT7925 BT after suspend/resume

LOG_FILE="/var/log/mt7925-bt-fix.log"
RELOAD_SCRIPT="/usr/bin/mt7925-bt-fix-reload.sh"

case $1 in
    pre)
        modprobe -r btusb btmtk mt7925e 2>/dev/null
        ;;
    post)
        # Use the reload script if available, otherwise inline
        if [[ -x "$RELOAD_SCRIPT" ]]; then
            "$RELOAD_SCRIPT"
        else
            modprobe -r btusb btmtk mt7925e 2>/dev/null
            sleep 1
            modprobe mt7925e
            sleep 1
            modprobe btmtk
            modprobe btusb
            sleep 1
        fi
        # Check if BT is working
        if [[ -d /sys/class/bluetooth ]] && [[ -n "$(ls -A /sys/class/bluetooth 2>/dev/null)" ]]; then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] BT restored after resume" >> "$LOG_FILE"
        fi
        ;;
esac
EOF
		error "Failed to create ${SLEEP_HOOK}"
		exit 1
	}
	chmod +x "$SLEEP_HOOK"
	success "Created ${SLEEP_HOOK}"

	# Reload systemd and enable service with error handling
	if ! systemctl daemon-reload; then
		error "Failed to reload systemd"
		exit 1
	fi

	if ! systemctl enable "${SERVICE_NAME}"; then
		error "Failed to enable ${SERVICE_NAME}"
		exit 1
	fi
	success "Enabled ${SERVICE_NAME}"

	# Run the fix now
	info "Running fix now..."
	reload_modules

	# Wait for adapter with retry
	if wait_for_bt_adapter 3; then
		success "Bluetooth adapter found!"
	elif systemctl is-active --quiet bluetooth && bluetoothctl list 2>/dev/null | grep -q "Controller"; then
		success "Bluetooth service active with controller"
	else
		info "Module loaded. Will retry on next boot."
		if ! systemctl is-active --quiet bluetooth; then
			info "Starting bluetooth service..."
			systemctl start bluetooth 2>/dev/null || true
		fi
		print_powercycle_reminder
	fi

	success "Installation complete!"
	echo ""
	echo "To apply the fix and check status:"
	echo "  sudo systemctl restart ${SERVICE_NAME}"
	echo "  sudo ./${0##*/} status"
	echo ""
	echo "To view logs:"
	echo "  sudo ./${0##*/} logs"
	echo ""
	echo "Reboot recommended to ensure fix applies on boot."
}

# Uninstall the fix
do_uninstall() {
	check_root

	info "Uninstalling MT7925 BT fix..."

	systemctl stop "${SERVICE_NAME}" 2>/dev/null || true
	systemctl disable "${SERVICE_NAME}" 2>/dev/null || true

	rm -f "$SERVICE_FILE" 2>/dev/null || true
	rm -f "$SLEEP_HOOK" 2>/dev/null || true
	rm -f "$MODULE_RELOAD_SCRIPT" 2>/dev/null || true

	# Clean up log file
	rm -f "$LOG_FILE" 2>/dev/null || true

	systemctl daemon-reload

	success "Uninstalled successfully"
}

# Show status
do_status() {
	echo "=== MT7925 Bluetooth Status ==="
	echo ""

	# Check if running as root for full output
	if [[ $EUID -eq 0 ]]; then
		# Full output for root
		echo "Hardware:"
		local hw_info
		hw_info=$(lspci -nn 2>/dev/null | grep -iE 'mt79|wireless|bluetooth')
		if [[ -n "$hw_info" ]]; then
			echo "$hw_info" | sed 's/^/  /'
		else
			echo "  No MT7925 found"
		fi
		echo ""

		# Check modules
		echo "Loaded modules:"
		if lsmod | grep -qE 'mt7925|btmtk|btusb|bluetooth'; then
			lsmod | grep -E 'mt7925|btmtk|btusb|bluetooth' | sed 's/^/  /'
		else
			echo "  None"
		fi
		echo ""

		# Check bluetooth class
		echo "Bluetooth sysfs:"
		if [[ -d /sys/class/bluetooth ]]; then
			local bt_device_count
			bt_device_count=$(ls -A /sys/class/bluetooth 2>/dev/null | wc -l | tr -d ' ')
			if [[ $bt_device_count -gt 0 ]]; then
				echo -e "  ${GREEN}✓ Bluetooth adapter found ($bt_device_count device(s))${NC}"
				ls /sys/class/bluetooth/ | sed 's/^/    /'
			else
				echo -e "  ${YELLOW}⚠ /sys/class/bluetooth exists but empty${NC}"
			fi
		else
			echo -e "  ${RED}✗ /sys/class/bluetooth not found${NC}"
		fi
		echo ""

		# Check service
		echo "Service status:"
		if [[ -f "$SERVICE_FILE" ]]; then
			if systemctl is-enabled "${SERVICE_NAME}" &>/dev/null; then
				echo -e "  ${GREEN}✓ ${SERVICE_NAME} is enabled${NC}"
				systemctl status "${SERVICE_NAME}" --no-pager | sed 's/^/  /'
			else
				echo -e "  ${YELLOW}⚠ ${SERVICE_NAME} is installed but not enabled${NC}"
			fi
		else
			echo -e "  ${YELLOW}⚠ ${SERVICE_NAME} not installed${NC}"
		fi
		echo ""

		# Check bluetooth service
		echo "Bluetooth service:"
		if systemctl is-active --quiet bluetooth; then
			echo -e "  ${GREEN}✓ bluetooth service is active${NC}"
		else
			echo -e "  ${YELLOW}⚠ bluetooth service not active${NC}"
		fi
		echo ""

		# Try bluetoothctl
		echo "Bluetoothctl:"
		if command -v bluetoothctl &>/dev/null; then
			local bt_list
			bt_list=$(bluetoothctl list 2>/dev/null)
			if echo "$bt_list" | grep -q "Controller"; then
				echo -e "  ${GREEN}✓ BT controller detected${NC}"
				echo "$bt_list" | sed 's/^/  /'
			else
				echo -e "  ${RED}✗ No BT controller${NC}"
				echo "  Run: sudo systemctl start bluetooth"
			fi
		else
			echo "  bluetoothctl not installed"
		fi
	else
		# Limited output for non-root
		echo "  (Run with sudo for full status)"
		echo ""
		echo "Hardware (limited):"
		local hw_info
		hw_info=$(lspci -nn 2>/dev/null | grep -iE 'mt79|wireless')
		if [[ -n "$hw_info" ]]; then
			echo "$hw_info" | sed 's/^/  /'
		else
			echo "  No MT7925 found"
		fi
		echo ""
		echo "Service: run with sudo to check"
		echo "Modules: run with sudo to check"
		echo ""
		if systemctl is-active --quiet bluetooth 2>/dev/null; then
			echo -e "  ${GREEN}✓ bluetooth service appears active${NC}"
		else
			echo -e "  ${YELLOW}⚠ bluetooth service may not be active${NC}"
		fi
	fi
}

# Test the fix
do_test() {
	check_root
	check_hardware

	info "Testing MT7925 BT fix..."
	print_powercycle_reminder

	# Reload modules
	reload_modules || true

	# Wait for adapter with more retries for test
	if wait_for_bt_adapter 5; then
		success "SUCCESS: Bluetooth adapter found!"
		echo "Adapters:"
		ls /sys/class/bluetooth/ | sed 's/^/  /'
		return 0
	else
		error "FAILED: No bluetooth adapter found after module reload"
		echo ""
		info "This is a known issue with MT7925. The module may need"
		info "multiple reloads, or a kernel/firmware update may be required."
		info ""
		info "Try running the test again - sometimes it takes multiple attempts."
		return 1
	fi
}

# Show logs
do_logs() {
	echo "=== MT7925 BT Fix Logs ==="
	echo ""

	if [[ -f "$LOG_FILE" ]]; then
		tail -50 "$LOG_FILE"
	else
		echo "No log file found at ${LOG_FILE}"
	fi

	echo ""
	echo "=== Systemd Service Logs ==="
	if [[ -f "$SERVICE_FILE" ]]; then
		# Show last 30 lines regardless of service state
		local logs
		logs=$(journalctl -u "${SERVICE_NAME}" --no-pager -n 30 2>&1)
		if [[ -n "$logs" ]]; then
			echo "$logs"
		else
			echo "No service logs found"
		fi
	else
		echo "Service not installed (${SERVICE_NAME})"
	fi
}

# Show help
show_help() {
	echo "MT7925 Bluetooth Fix Script"
	echo ""
	echo "Usage: sudo $0 [command]"
	echo ""
	echo "Commands:"
	echo "  install    Install the fix (creates service + sleep hook)"
	echo "  uninstall  Remove the fix"
	echo "  status     Check BT status and service state"
	echo "  test       Test the module reload manually"
	echo "  logs       View fix logs"
	echo "  help       Show this help"
	echo ""
}

# Main
case "${1:-help}" in
install)
	do_install
	;;
uninstall)
	do_uninstall
	;;
status)
	do_status
	;;
test)
	do_test
	;;
logs)
	do_logs
	;;
help | --help | -h | "")
	show_help
	;;
*)
	error "Unknown command: $1"
	show_help
	exit 1
	;;
esac
